use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gabbler, GabblerWeb.Endpoint,
  http: [
    port: 8080,
    compress: true,
    protocol_options: [
      max_header_name_length: 128,
      max_header_value_length: 8192,
      max_headers: 100
    ]
  ],
  url: [host: "smileys.pub", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:gabbler, :vsn)

# Do not print debug messages in production
config :logger, level: :error

config :phoenix, :serve_endpoints, true

config :gabbler_data,
  ecto_repos: [GabblerData.Repo]


import_config "prod.secret.exs"